# This file was generated by GoReleaser. DO NOT EDIT.
cask "aice" do
  require "download_strategy"

  class GitHubPrivateRepositoryReleaseDownloadStrategy < CurlDownloadStrategy
    def initialize(url, name, version, **meta)
      @url = url
      parse_url_pattern
      set_github_token
      meta[:headers] ||= []
      meta[:headers] << "Accept: application/octet-stream"
      meta[:headers] << "Authorization: Bearer #{@github_token}"
      api_url = "https://api.github.com/repos/#{@owner}/#{@repo}/releases/assets/#{asset_id}"
      super(api_url, name, version, **meta)
    end

    def parse_url_pattern
      pattern = %r{https://github\.com/([^/]+)/([^/]+)/releases/download/([^/]+)/(\S+)}
      raise CurlDownloadStrategyError, "Invalid GitHub release URL: #{@url}" unless @url =~ pattern

      _, @owner, @repo, @tag, @filename = *@url.match(pattern)
    end

    private

    def set_github_token
      @github_token = ENV["HOMEBREW_GITHUB_API_TOKEN"]
      @github_token = GitHub::API.credentials if (@github_token.nil? || @github_token.empty?) && defined?(GitHub::API)
      if @github_token.nil? || @github_token.empty?
        raise CurlDownloadStrategyError,
          "No GitHub credentials for the private aice repo. Run `gh auth login` or export HOMEBREW_GITHUB_API_TOKEN (repo scope)."
      end
      GitHub.repository(@owner, @repo)
    end

    def asset_id
      @asset_id ||= begin
        assets = GitHub.get_release(@owner, @repo, @tag)["assets"]
        asset = assets.find { |a| a["name"] == @filename }
        raise CurlDownloadStrategyError, "Asset #{@filename} not found in release #{@tag}" if asset.nil?

        asset["id"]
      end
    end
  end

  version "0.1.5"

  on_macos do
    on_intel do
      sha256 "f4cb1f893c0adcc6b6c18980ecc34e74b6ad09ff21a70153bcd1db4f6d3486eb"
      url "https://github.com/propra-tech/aice/releases/download/v#{version}/aice_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/propra-tech/aice/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
    on_arm do
      sha256 "f5d5bce5d1e4c9e2952a90bd844ae82378aa69ce56c82ea6ea2e2b08b3ca5c0b"
      url "https://github.com/propra-tech/aice/releases/download/v#{version}/aice_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/propra-tech/aice/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
  end

  on_linux do
    on_intel do
      sha256 "01ac80215cb2c987cca0c4e2ee2544ec77ab50e1ebfc0662e295b57ded875d73"
      url "https://github.com/propra-tech/aice/releases/download/v#{version}/aice_#{version}_linux_amd64.tar.gz",
        verified: "github.com/propra-tech/aice/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
    on_arm do
      sha256 "6dd8aa61cee80c4d353a23bb8d002d79ae4d5e222f3705eac956d7a20452d2c4"
      url "https://github.com/propra-tech/aice/releases/download/v#{version}/aice_#{version}_linux_arm64.tar.gz",
        verified: "github.com/propra-tech/aice/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
  end

  name "aice"
  desc "Author and manage pages on the Propra intranet (aice)"
  homepage "https://github.com/propra-tech/aice"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aice"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aice"]
    end
  end

  # No zap stanza required

end
