# This file was generated by GoReleaser. DO NOT EDIT.
cask "aice" do
  require "download_strategy"

  class GitHubPrivateRepositoryReleaseDownloadStrategy < CurlDownloadStrategy
    def initialize(url, name, version, **meta)
      @url = url
      parse_url_pattern
      set_github_token
      meta[:headers] ||= []
      meta[:headers] << "Accept: application/octet-stream"
      meta[:headers] << "Authorization: Bearer #{@github_token}"
      api_url = "https://api.github.com/repos/#{@owner}/#{@repo}/releases/assets/#{asset_id}"
      super(api_url, name, version, **meta)
    end

    def parse_url_pattern
      pattern = %r{https://github\.com/([^/]+)/([^/]+)/releases/download/([^/]+)/(\S+)}
      raise CurlDownloadStrategyError, "Invalid GitHub release URL: #{@url}" unless @url =~ pattern

      _, @owner, @repo, @tag, @filename = *@url.match(pattern)
    end

    private

    def set_github_token
      @github_token = ENV["HOMEBREW_GITHUB_API_TOKEN"]
      @github_token = GitHub::API.credentials if (@github_token.nil? || @github_token.empty?) && defined?(GitHub::API)
      if @github_token.nil? || @github_token.empty?
        raise CurlDownloadStrategyError,
          "No GitHub credentials for the private aice repo. Run `gh auth login` or export HOMEBREW_GITHUB_API_TOKEN (repo scope)."
      end
      GitHub.repository(@owner, @repo)
    end

    def asset_id
      @asset_id ||= begin
        assets = GitHub.get_release(@owner, @repo, @tag)["assets"]
        asset = assets.find { |a| a["name"] == @filename }
        raise CurlDownloadStrategyError, "Asset #{@filename} not found in release #{@tag}" if asset.nil?

        asset["id"]
      end
    end
  end

  version "0.1.8"

  on_macos do
    on_intel do
      sha256 "03076d54e1dfdf8e07fc9214972f4f806069f0ee23b350e6764f92cb8f4b517e"
      url "https://github.com/propra-tech/aice/releases/download/v#{version}/aice_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/propra-tech/aice/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
    on_arm do
      sha256 "479d2a90d383200d3ef90a90a764f5ceb3e2ff76fe92e23ea93da762c56ff0d2"
      url "https://github.com/propra-tech/aice/releases/download/v#{version}/aice_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/propra-tech/aice/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
  end

  on_linux do
    on_intel do
      sha256 "02e975e751cc8d37fb0557050608be577fb86dd1c41f43989012901e5f423fa1"
      url "https://github.com/propra-tech/aice/releases/download/v#{version}/aice_#{version}_linux_amd64.tar.gz",
        verified: "github.com/propra-tech/aice/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
    on_arm do
      sha256 "fe6140f246887862cdfc62f3ca0e1bd63889fcb6b8291c18332c885ebc6f27f3"
      url "https://github.com/propra-tech/aice/releases/download/v#{version}/aice_#{version}_linux_arm64.tar.gz",
        verified: "github.com/propra-tech/aice/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
  end

  name "aice"
  desc "Author and manage pages on the Propra intranet (aice)"
  homepage "https://github.com/propra-tech/aice"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aice"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aice"]
    end
  end

  # No zap stanza required

end
