# This file was generated by GoReleaser. DO NOT EDIT.
cask "aice" do
  require "download_strategy"

  class GitHubPrivateRepositoryReleaseDownloadStrategy < CurlDownloadStrategy
    def initialize(url, name, version, **meta)
      @url = url
      parse_url_pattern
      set_github_token
      meta[:headers] ||= []
      meta[:headers] << "Accept: application/octet-stream"
      meta[:headers] << "Authorization: Bearer #{@github_token}"
      api_url = "https://api.github.com/repos/#{@owner}/#{@repo}/releases/assets/#{asset_id}"
      super(api_url, name, version, **meta)
    end

    def parse_url_pattern
      pattern = %r{https://github\.com/([^/]+)/([^/]+)/releases/download/([^/]+)/(\S+)}
      raise CurlDownloadStrategyError, "Invalid GitHub release URL: #{@url}" unless @url =~ pattern

      _, @owner, @repo, @tag, @filename = *@url.match(pattern)
    end

    private

    def set_github_token
      @github_token = ENV["HOMEBREW_GITHUB_API_TOKEN"]
      @github_token = GitHub::API.credentials if (@github_token.nil? || @github_token.empty?) && defined?(GitHub::API)
      if @github_token.nil? || @github_token.empty?
        raise CurlDownloadStrategyError,
          "No GitHub credentials for the private aice repo. Run `gh auth login` or export HOMEBREW_GITHUB_API_TOKEN (repo scope)."
      end
      GitHub.repository(@owner, @repo)
    end

    def asset_id
      @asset_id ||= begin
        assets = GitHub.get_release(@owner, @repo, @tag)["assets"]
        asset = assets.find { |a| a["name"] == @filename }
        raise CurlDownloadStrategyError, "Asset #{@filename} not found in release #{@tag}" if asset.nil?

        asset["id"]
      end
    end
  end

  version "0.17.4"

  on_macos do
    on_intel do
      sha256 "46e9dece6d7e2b36fd4fc97ce1a35adcf219f8f3864c72f561605c51103cab01"
      url "https://github.com/aice-x/aice/releases/download/v#{version}/aice_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/aice-x/aice/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
    on_arm do
      sha256 "0c8a85e460a468e93e793ebfe59c074ac5e4b21d6365cc9d6822e80b5e5f672c"
      url "https://github.com/aice-x/aice/releases/download/v#{version}/aice_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/aice-x/aice/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
  end

  on_linux do
    on_intel do
      sha256 "209e806ca40ffdc47acc099d0f92d281edfda61deb970ca7fc97934b056d348f"
      url "https://github.com/aice-x/aice/releases/download/v#{version}/aice_#{version}_linux_amd64.tar.gz",
        verified: "github.com/aice-x/aice/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
    on_arm do
      sha256 "e9c2f84e0fc875baea9fd15e2ed6694565e785a1d79afb3b6a6b4716d4c96b13"
      url "https://github.com/aice-x/aice/releases/download/v#{version}/aice_#{version}_linux_arm64.tar.gz",
        verified: "github.com/aice-x/aice/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
  end

  name "aice"
  desc "Author and manage pages on your organization's aice intranet"
  homepage "https://github.com/aice-x/aice"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aice"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aice"]
    end
  end

  # No zap stanza required

end
